### PR TITLE
Tests for proposal code script

### PR DESCRIPTION
**Pull request by Lonwabo11**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/22)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/22)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[saltapi/repository/proposal_repository.py, line 15 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRl6Pk83f9L79CG7gA:-MQRl6Pk83f9L79CG7gB:b53g3ym) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/saltapi/repository/proposal_repository.py#L15)):*
> ```Python
>         file = archive.open("Proposal.xml")
>     except FileNotFoundError:
>         raise KeyError("There is no item named 'Proposal.xml' in the archive") from None
> ```

I don't think this should be a KeyError.
___
*[saltapi/repository/proposal_repository.py, line 22 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlEPo3MRpQwN8Icxn:-MQRlEPo3MRpQwN8Icxo:b-6h6r79) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/saltapi/repository/proposal_repository.py#L22)):*
> ```Python
>         raise ValueError("No proposal code supplied in the file Proposal.xml.")
> 
>     is_file_zipped = zipfile.is_zipfile(user_proposal)
> ```

Can be inlined.
___
*[saltapi/repository/proposal_repository.py, line 26 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlHsKDKTdsJBY39TK:-MQRlHsKDKTdsJBY39TL:blbyeat) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/saltapi/repository/proposal_repository.py#L26)):*
> ```Python
>         raise ValueError("The file supplied is not a zip file")
> 
>     if proposal.tag.split("}")[1] != "Proposal":
> ```

Ideally you would support XML without namespaces as well. (And you should test this.)
___
*[tests/test_proposal_code.py, line 35 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlY5D6_0Rbi6l2aII:-MQRlY5D6_0Rbi6l2aIJ:b-114yr3) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L35)):*
> ```Python
>     with ZipFile(archive, 'w') as zip_file:
>         with zip_file.open("Proposal.xml", "w") as proposal_file:
>             proposal_file.write(b'''<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
> ```

Can be simplified: at most one namespace, define XML in unit test functions.
___
*[tests/test_proposal_code.py, line 128 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlljT8TOyX0uVl3s9:-MQRlljT8TOyX0uVl3sA:bp1bce3) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L128)):*
> ```Python
> 
> def test_root_element_has_no_proposal_code():
>     file = zipfile_no_proposal_code()
> ```

You should a comments briefly describing what your unit tests are testing.
___
*[tests/test_proposal_code.py, line 129 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRiq43A1QZfpXmOfrE:-MQRiq448EyxuLSviLfj:b-8ofdqz) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L129)):*
> ```Python
> def test_root_element_has_no_proposal_code():
>     file = zipfile_no_proposal_code()
>     with pytest.raises(ValueError) as execinfo:
> ```

execinfo ---> excinfo (everywhere in this file)
___
*[tests/test_proposal_code.py, line 148 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRmwh8BVhdJo1Nnc7m:-MQRmwh8BVhdJo1Nnc7n:bewjy6s) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L148)):*
> ```Python
> 
> 
> def test_valid_proposal_code():
> ```

It seems you are not testing invalid proposal codes?

Also, you should test more examples.
___
*[tests/test_proposal_code.py, line 158 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlzNy3GhQmy9ZedHe:-MQRlzNy3GhQmy9ZedHf:bokn1nq) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L158)):*
> ```Python
> 
> 
> def test_root_element_is_called_proposal():
> ```

Should be called "test_root_element_is_not_called_proposal".
___
*[tests/test_proposal_code.py, line 162 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRmNeh5UQX107lJO2o:-MQRmNeh5UQX107lJO2p:bfekdr6) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L162)):*
> ```Python
>     with pytest.raises(ValueError) as execinfo:
>         get_proposal_code(file)
>     assert "The root element of your xml file is not called Proposal" in str(execinfo.value)
> ```

The root element of your xml file ---> The root element in the file Proposal.xml

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/22)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/proposal_repository.py, line 15 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRl6Pk83f9L79CG7gA:-MQVlARi9n31cdsWpmqL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/saltapi/repository/proposal_repository.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this should be a KeyError.
</blockquote></details>

Done.
___
*[saltapi/repository/proposal_repository.py, line 22 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlEPo3MRpQwN8Icxn:-MQVlK0k-dzbtp4UJQFX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/saltapi/repository/proposal_repository.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be inlined.
</blockquote></details>

Done.
___
*[saltapi/repository/proposal_repository.py, line 26 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlHsKDKTdsJBY39TK:-MQWPdg380OrOnGdZUzB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/saltapi/repository/proposal_repository.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ideally you would support XML without namespaces as well. (And you should test this.)
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 35 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlY5D6_0Rbi6l2aII:-MQWPbXUCUuVTvf-S1FT:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be simplified: at most one namespace, define XML in unit test functions.
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 128 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlljT8TOyX0uVl3s9:-MQVpN3K7F5dGTC7m7Su:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should a comments briefly describing what your unit tests are testing.
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 129 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRiq43A1QZfpXmOfrE:-MQVntsNBVFRmNk0Ey7k:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L129)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

execinfo ---> excinfo (everywhere in this file)
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 148 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRmwh8BVhdJo1Nnc7m:-MQWPYj77viI8A97bSVu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L148)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems you are not testing invalid proposal codes?

Also, you should test more examples.
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 158 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRlzNy3GhQmy9ZedHe:-MQWPBGW8RxurxE449LJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be called "test_root_element_is_not_called_proposal".
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 162 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRmNeh5UQX107lJO2o:-MQWPWHJ0IIAdN_zqmC3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The root element of your xml file ---> The root element in the file Proposal.xml
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/22)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[saltapi/repository/proposal_repository.py, line 9 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWweQjDauFwwTYt-KQ:-MQWweQjDauFwwTYt-KR:b27p07n) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/saltapi/repository/proposal_repository.py#L9)):*
> ```Python
> 
> 
> def get_proposal_code(user_proposal: Union[str, BinaryIO]) -> Optional[str]:
> ```

user_proposal ---> proposal or proposal_zip
___
*[saltapi/repository/proposal_repository.py, line 15 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWw_NNDHm19seYhXmS:-MQWw_NNDHm19seYhXmT:bxdx1am) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/saltapi/repository/proposal_repository.py#L15)):*
> ```Python
>         file = archive.open("Proposal.xml")
>     except KeyError:
>         raise KeyError("No file called Proposal.xml was found") from None
> ```

"The zip file contains no file Proposal.xml."
___
*[saltapi/repository/proposal_repository.py, line 22 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWvz8nA94FcUgbSn_p:-MQWvz8o4O5YSqAwJ9Qo:b-zfcb58) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/saltapi/repository/proposal_repository.py#L22)):*
> ```Python
>         raise ValueError("No proposal code supplied in the file Proposal.xml.")
> 
>     if not zipfile.is_zipfile(user_proposal):
> ```

You are unzipping the file before you actually test whether it is a zip file. So this code has to move up...
___
*[tests/test_proposal_code.py, line 148 at r2](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQRmwh8BVhdJo1Nnc7m:-MQWzROj-KKqW1SJwdts:bnpzjpm) ([raw file](https://github.com/saltastroops/salt-api/blob/2c4770793c6624ae5bd1833a4110fff92a1d6ff9/tests/test_proposal_code.py#L148)):*
<details><summary><i>Previously, Lonwabo11 (Lonwabo Zaula) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe we should have another quick chat about this... :)
___
*[tests/test_proposal_code.py, line 1 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWwIQG5AHwvz25UIof:-MQWwIQG5AHwvz25UIog:b-7yt3pq) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L1)):*
> ```Python
> from zipfile import ZipFile
> ```

Missing: a unit test for the case that the supplied file is no zip file.
___
*[tests/test_proposal_code.py, line 7 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWxX_D4JU4pSJcovjB:-MQWxX_D4JU4pSJcovjC:b-bwie33) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L7)):*
> ```Python
> 
> 
> def create_zip(xml: bytes, filename: str):
> ```

You could consider using a default value (namely "Proposal.xml") for the filename parameter.
___
*[tests/test_proposal_code.py, line 43 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWy4yV7ROeO-7dVk9U:-MQWy4yV7ROeO-7dVk9V:b-c95ccx) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L43)):*
> ```Python
> 
> 
> def test_proposal_code_is_unsubmitted():
> ```

test_proposal_code_is_unsubmitted and test_proposal_code_as_empty_string can be combined.
___
*[tests/test_proposal_code.py, line 69 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWz_X66XirdYE0cqTK:-MQWz_X66XirdYE0cqTL:b-csnrz2) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L69)):*
> ```Python
> 
> @pytest.mark.parametrize("code, output", [("12", "Invalid proposal code: 12")])
> def test_wrong_proposal_code(code, output):
> ```

"invalid" might be better than "wrong".
___
*[tests/test_proposal_code.py, line 79 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWzFkqATBdDMLxFu4B:-MQWzFkqATBdDMLxFu4C:b-hjxkhf) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L79)):*
> ```Python
> 
> @pytest.mark.parametrize("code, output", [("submitted", "Invalid proposal code: submitted")])
> def test_wrong_proposal_code_with_xml_namespace(code, output):
> ```

I would rather test namespaces with a valid proposal code.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/22)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/proposal_repository.py, line 9 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWweQjDauFwwTYt-KQ:-MQpVMc56oueNkbTC2PJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/saltapi/repository/proposal_repository.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

user_proposal ---> proposal or proposal_zip
</blockquote></details>

Done.
___
*[saltapi/repository/proposal_repository.py, line 15 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWw_NNDHm19seYhXmS:-MQpVXaOD9Rfbc_XCboF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/saltapi/repository/proposal_repository.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"The zip file contains no file Proposal.xml."
</blockquote></details>

Done.
___
*[saltapi/repository/proposal_repository.py, line 22 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWvz8nA94FcUgbSn_p:-MQpVaWCCO3LlPOsFrrD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/saltapi/repository/proposal_repository.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are unzipping the file before you actually test whether it is a zip file. So this code has to move up...
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 1 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWwIQG5AHwvz25UIof:-MQpZ-5s5D5E97YYSyXt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Missing: a unit test for the case that the supplied file is no zip file.
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 7 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWxX_D4JU4pSJcovjB:-MQpZ0nHEqMbRF1U3qfG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could consider using a default value (namely "Proposal.xml") for the filename parameter.
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 43 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWy4yV7ROeO-7dVk9U:-MQpZjCq48YBN0Q9ZDwx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

test_proposal_code_is_unsubmitted and test_proposal_code_as_empty_string can be combined.
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 69 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWz_X66XirdYE0cqTK:-MQp_0NPBDWdPCHk9vDi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"invalid" might be better than "wrong".
</blockquote></details>

Done.
___
*[tests/test_proposal_code.py, line 79 at r3](https://reviewable.io/reviews/saltastroops/salt-api/22#-MQWzFkqATBdDMLxFu4B:-MQpmAaI2zdzzr_F41jm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff28facd8d804f20a84f0bc937a43bbd8358c3bf/tests/test_proposal_code.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would rather test namespaces with a valid proposal code.
</blockquote></details>

Done.

**Review by Lonwabo11 — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/22)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
