### PR TITLE
To discuss

### PR DESCRIPTION
**Pull request by Eb-Zeero**
Do not merge This request

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/17)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/17)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/auth/authorization.py, line 105 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYgPWn-4tKYXOYaEgE:-MNYgPWo39wa2jlaBWzN:bosawg3) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L105)):*
> ```Python
> 
> 
> def has_permission(user: User, permission: Permission) -> bool:
> ```

This probably should be a method of the User class.
___
*[saltapi/auth/authorization.py, line 112 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYgyki3BmwhfCik2xQ:-MNYgyki3BmwhfCik2xR:b3lgj78) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L112)):*
> ```Python
> 
> 
> def can_submit_proposal(username: str, proposal_code: Optional[str] = None) -> None:
> ```

The name of the function suggests you return a boolean.
___
*[saltapi/auth/authorization.py, line 112 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYiFLZ3BbpY2JvBzKJ:-MNYiFLZ3BbpY2JvBzKK:bkqd6qa) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L112)):*
> ```Python
> 
> 
> def can_submit_proposal(username: str, proposal_code: Optional[str] = None) -> None:
> ```

I'd rather pass the user than the username.
___
*[saltapi/auth/authorization.py, line 129 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYhW5CCe74VbXVoXIx:-MNYhW5CCe74VbXVoXIy:b-gaag9l) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L129)):*
> ```Python
> 
>     """
>     if not is_user_verified:
> ```

Should not be necessary.
___
*[saltapi/auth/authorization.py, line 131 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYhJFF9YD_rMPVDTNt:-MNYhJFF9YD_rMPVDTNu:b-m6k4ye) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L131)):*
> ```Python
>     if not is_user_verified:
>         raise Exception("User not verified.")
>     if not proposal_code:  # Might be a new proposal
> ```

Might be ---> Is
___
*[saltapi/auth/authorization.py, line 137 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYhxJl0L1uEJ_kod8G:-MNYhxJl0L1uEJ_kod8H:b-kjtauz) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L137)):*
> ```Python
>     if is_user_pc(username, proposal_code):  # User is a principal contact
>         return
>     raise Exception("User do not own the proposal.")
> ```

"Only the Principal Investigator and Principal Contact may resubmit a proposal."
___
*[saltapi/auth/authorization.py, line 153 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYiRVn3EF1BmZyKv2D:-MNYiRVn3EF1BmZyKv2E:bgnrgap) ([raw file](https://github.com/saltastroops/salt-api/blob/214433c7e7f0471d18e80df71d36e5a04361fd6f/saltapi/auth/authorization.py#L153)):*
> ```Python
> 
>     """
>     if is_user_pi(username, proposal_code):
> ```

You should check that the user has the permission to submit.
___
*[saltapi/graphql/directives.py, line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYfmF5-c-w2HGPBE6e:-MNYfmF5-c-w2HGPBE6f:bxc6m9o) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/graphql/directives.py#L20)):*
> ```Python
> 
> 
> class PermittedForDirective(SchemaDirectiveVisitor):
> ```

The directive should be removed, as authorisation is handled by the resolvers.

But... there might be a directive for checking that the user is authenticated.
___
*[saltapi/repository/user_repository.py, line 150 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYikn_4M1cdPqvgRpF:-MNYikn_4M1cdPqvgRpG:bek5i0u) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/repository/user_repository.py#L150)):*
> ```Python
> 
> 
> async def is_user_verified(username: str) -> bool:
> ```

Should not be necessary. (And the docstring would have to be updated. :) )
___
*[saltapi/submission/submit.py, line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYiyg2-LDXGK2lYMGf:-MNYiyg2-LDXGK2lYMGg:bhwu789) ([raw file](https://github.com/saltastroops/salt-api/blob/214433c7e7f0471d18e80df71d36e5a04361fd6f/saltapi/submission/submit.py#L27)):*
> ```Python
>     if proposal_code:
>         data["proposal_code"] = proposal_code
>     user = User(
> ```

This user definition was intentional... :-)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/17)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/auth/authorization.py, line 112 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYiFLZ3BbpY2JvBzKJ:-MNYmvNfDoBrLlQxCdQO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L112)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather pass the user than the username.
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 129 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYhW5CCe74VbXVoXIx:-MNYn2nz5bhJ8EC4x7YN:bjmm0uj) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L129)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be necessary.
</blockquote></details>

Proposal can not be submitted if user not verified.
___
*[saltapi/auth/authorization.py, line 131 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYhJFF9YD_rMPVDTNt:-MNYnYho1pP07lWEd2qE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L131)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might be ---> Is
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 137 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYhxJl0L1uEJ_kod8G:-MNYqec3BHPJ8a6iF1Rl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/auth/authorization.py#L137)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Only the Principal Investigator and Principal Contact may resubmit a proposal."
</blockquote></details>

Done.
___
*[saltapi/graphql/directives.py, line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYfmF5-c-w2HGPBE6e:-MNYqa1g22RCynKZHCFo:b-oblgzi) ([raw file](https://github.com/saltastroops/salt-api/blob/85fad18fd53794835b7d9fc0b635e872ee490ff4/saltapi/graphql/directives.py#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The directive should be removed, as authorisation is handled by the resolvers.

But... there might be a directive for checking that the user is authenticated.
</blockquote></details>

I will remove code when we are both happy
___
*[saltapi/submission/submit.py, line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYiyg2-LDXGK2lYMGf:-MNYqSOD0UBArrqaLJ0n:bsvlcrz) ([raw file](https://github.com/saltastroops/salt-api/blob/214433c7e7f0471d18e80df71d36e5a04361fd6f/saltapi/submission/submit.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This user definition was intentional... :-)
</blockquote></details>

brought back

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/17)* status: all files reviewed, 13 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/graphql/directives.py, line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNbmSA234JlAXCaNy44:-MNbmSA234JlAXCaNy45:b-6rs4cl) ([raw file](https://github.com/saltastroops/salt-api/blob/fd3730055c4e627f3d141bb82dffff0243f4a6a5/saltapi/graphql/directives.py#L14)):*
> ```Python
> 
> 
> class IsAuthenticatedDirective(SchemaDirectiveVisitor):
> ```

Should be called something like AuthRequiredDirective.
___
*[saltapi/graphql/directives.py, line 28 at r2](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNbnDc3DVRrxhlwQZh5:-MNbnDc3DVRrxhlwQZh6:bkwpg34) ([raw file](https://github.com/saltastroops/salt-api/blob/fd3730055c4e627f3d141bb82dffff0243f4a6a5/saltapi/graphql/directives.py#L28)):*
> ```Python
> 
>             auth = args[1].context["request"].auth
>             if "authenticated" not in auth.scopes:
> ```

I'd suggest you use the is_authenticated property of the user object for checking. See [https://www.starlette.io/authentication/](https://www.starlette.io/authentication/).
___
*[saltapi/graphql/schema.graphql, line 28 at r2](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNc5af875YMQpdlEBTh:-MNc5af875YMQpdlEBTi:b1zequf) ([raw file](https://github.com/saltastroops/salt-api/blob/fd3730055c4e627f3d141bb82dffff0243f4a6a5/saltapi/graphql/schema.graphql#L28)):*
> ```GraphQL
> type Proposal {
>   content(proposalCode: ProposalCode): String!
>                 @isAuthenticated(roles=[PROPOSAL_OWNER], permissions=[VIEW_ALL_PROPOSALS])
> ```

The directive should have no arguments
___
*[saltapi/graphql/schema.graphql, line 37 at r2](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNc5zGOCwxslki4XMgq:-MNc5zGOCwxslki4XMgr:b-55ngb2) ([raw file](https://github.com/saltastroops/salt-api/blob/fd3730055c4e627f3d141bb82dffff0243f4a6a5/saltapi/graphql/schema.graphql#L37)):*
> ```GraphQL
> The directive uses the arguments of the field resolver as required.
> """
> directive @isAuthenticated on FIELD_DEFINITION
> ```

Should be called something like @authRequired
___
*[saltapi/submission/submit.py, line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNYiyg2-LDXGK2lYMGf:-MNc6RhP-BZFi2FOEJSI:bdtufbu) ([raw file](https://github.com/saltastroops/salt-api/blob/214433c7e7f0471d18e80df71d36e5a04361fd6f/saltapi/submission/submit.py#L27)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

brought back
</blockquote></details>

But you forgot the "Admin" in the roles list. :)

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/17)* status: all files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/auth/authorization.py, line 76 at r2](https://reviewable.io/reviews/saltastroops/salt-api/17#-MNeKcOI1teSa7qX-nD6:-MNeKcOJ-7p2Ku_UMrcl:b5qewj9) ([raw file](https://github.com/saltastroops/salt-api/blob/fd3730055c4e627f3d141bb82dffff0243f4a6a5/saltapi/auth/authorization.py#L76)):*
> ```Python
> 
> 
> def can_submit_proposal(user: User, proposal_code: Optional[str] = None) -> bool:
> ```

This function probably should move. Let's have a chat about this.

**Pull request closed without merging**
